### PR TITLE
Fix copyright & desc

### PR DESCRIPTION
**Pull request by Odyssey346**

### CODE REVIEW

**Comment by Odyssey346** [comment]
why is that commit here?

**Comment by hellcp** [comment]
I mean, everything but the index page searches openSUSE infrastructure

**Comment by Odyssey346** [comment]
what would be a more appropriate description, then?

**Comment by hellcp** [comment]
I'm not sure

**Comment by Odyssey346** [comment]
I guess "Search everything openSUSE & the internet"

**Pull request merged**
