### PR TITLE
Change default search engine to DuckDuckGo

### PR DESCRIPTION
**Pull request by coogor**
DDG is a bit more privacy-friendly compared to google, thus more in line with our philosophy

### CODE REVIEW

**Comment by okurz** [comment]
I like it. I can also recommend https://info.ecosia.org/privacy with the additional benefit of support a climate friendly company.

In your commit message I recommend to fix the typo s/serach/search/

**Review by coogor — COMMENTED** [review]
typo corrected

**Comment by coogor** [comment]
> In your commit message I recommend to fix the typo s/serach/search/
Done, thanks Oliver!

**Comment by okurz** [comment]
@coogor sorry, you only changed the *pull request title*, not the *git commit message*

**Comment by TheEvilSkeleton** [comment]
> I like it. I can also recommend https://info.ecosia.org/privacy with the additional benefit of support a climate friendly company.
> 
> In your commit message I recommend to fix the typo s/serach/search/

I second this!

**Comment by hellcp** [comment]
How are non-english results in ddg or ecosia? Last I verified it, it absolutely sucked for searching for terms in different languages, especially with terms that may have coverage in both english and another language. ddg also very frequently suggests technical answers, which is perfect for people like us, developers, and less for a person that may be using openSUSE distros due to being subjected to it by family

**Comment by coogor** [comment]
Well, if you need special topics you may even want to use a specialized search engine. I feel ddg is a common denominator - as everybody thought about it for more than 3 weeks, can we set it live before Leap 15.3?

**Pull request merged**
